### ISSUE TITLE
mt_dnn_base.pt

### ISSUE THREAD

**Issue by ZhaofengWu** [namisan/mt-dnn#10]
Is the downloaded `mt_dnn_base.pt` the same as the resulting model after running `scripts/run_mt_dnn.sh`? If not, what is their relationship?

**Comment by namisan** [comment]
It is trained on the similar way. However, one is a base model, and the other is a large model.

**Comment by ZhaofengWu** [comment]
Then is the resulting model the same as the downloaded `bert_model_large.pt`?

**Comment by eecrazy** [comment]
I also have the same question. Is the mt_dnn_base.pt model downloaded from https://mrc.blob.core.windows.net/mt-dnn-model/mt_dnn_base.pt resulted from multi-task training described in the paper?
I got very poor results on my own task from mt_dnn_base.pt model. No better than fine-tuning from the original bert-base model.

**Comment by namisan** [comment]
I'm not sure how did you train the model.
Here is the log.
https://github.com/namisan/mt-dnn/issues/18

**Comment by Akshayextreme** [comment]
> Is the downloaded `mt_dnn_base.pt` the same as the resulting model after running `scripts/run_mt_dnn.sh`? If not, what is their relationship?

From where you downloaded released `mt_dnn_base.pt` ? I am not able find it anywhere

**Comment by namisan** [comment]
@Akshayextreme 
Please find attached. 
https://github.com/namisan/mt-dnn/blob/master/download.sh#L18
