### ISSUE TITLE
Sequence labeling task

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#102]
Hello,
regarding the suggested command for NER
python train.py --data_dir <data-path> --init_checkpoint <bert/ner-model> --train_dataset ner --test_dataset ner --task_def experiments\ner\ner_task_def.py

1) could you provide a specific example for the command ? It is not clear what we should put here: <bert/ner-model> . To my understadning, here ``` --train_dataset ner --test_dataset ner ``` where ```ner``` we should put the filename.

2) When running the command, what will happen? It will train NER as single task, using the shared layers that have been trained with the multitask?

My intention is to adapt it for a different sequence labeling task, from NER, and to use multitask learning for that.

Could you please help me understand?
Thanks

**Comment by antgr** [comment]
Also, one more serious issue:
In documentation says to run: $sh experiments/ner/prepro.py
but I suspect it means to say $python experiments/ner/prepro.py
But then:
$ python experiments/ner/prepro.py
Traceback (most recent call last):
  File "experiments/ner/prepro.py", line 7, in <module>
    from experiments.ner.ner_utils import load_conll_chunk, load_conll_ner, load_conll_pos, dump_rows
ImportError: cannot import name 'dump_rows' from 'experiments.ner.ner_utils' (/home/ant/multitask/mt-dnn/experiments/ner/ner_utils.py)

**Comment by namisan** [comment]
can you update to latest branch? you can follow instruct to cook NER data. Similarly, saying you also cook POS tagging data as NER. You can use command like --train_dataset ner,pos --test_dataset ner,pos. We'll write some tutorials for these soon.

**Comment by antgr** [comment]
@namisan Could you have a look in #116 ? It is related to this question. Thank you very much for your answers!
