### ISSUE TITLE
train toy example, dataset issue

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#103]
(mt-dnn) ant@ant-Z97M-DS3H:~/multitask/mt-dnn$ python train.py
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
Namespace(adam_eps=1e-06, answer_att_hidden_size=128, answer_att_type='bilinear', answer_dropout_p=0.1, answer_mem_drop_p=0.1, answer_mem_type=1, answer_merge_opt=1, answer_num_turn=5, answer_opt=0, answer_rnn_type='gru', answer_sum_att_type='bilinear', answer_weight_norm_on=False, batch_size=8, batch_size_eval=8, bert_dropout_p=0.1, bert_l2norm=0.0, cuda=True, data_dir='data/canonical_data/mt_dnn_uncased_lower', data_sort_on=False, dropout_p=0.1, dropout_w=0.0, dump_state_on=False, ema_gamma=0.995, ema_opt=0, embedding_opt=0, encoder_type=<EncoderModelType.BERT: 1>, epochs=5, fp16=False, fp16_opt_level='O1', freeze_layers=-1, global_grad_clipping=1.0, glue_format_on=False, grad_accumulation_step=1, grad_clipping=0, have_lr_scheduler=True, init_checkpoint='mt_dnn_models/bert_model_base.pt', init_ratio=1, label_size='3', learning_rate=5e-05, log_file='mt-dnn-train.log', log_per_updates=500, lr_gamma=0.5, max_seq_len=512, mem_cum_type='simple', mix_opt=0, model_ckpt='checkpoints/model_0.pt', momentum=0, mtl_opt=0, multi_gpu_on=False, multi_step_lr='10,20,30', name='farmer', optimizer='adamax', output_dir='checkpoint', ratio=0, resume=False, save_per_updates=10000, save_per_updates_on=False, scheduler_type='ms', seed=2018, task_def='experiments/glue/glue_task_def.yml', tensorboard=False, tensorboard_logdir='tensorboard_logdir', test_datasets=['mnli_mismatched', 'mnli_matched'], train_datasets=['mnli'], update_bert_opt=0, vb_dropout=True, warmup=0.1, warmup_schedule='warmup_linear', weight_decay=0)
10/15/2019 01:45:12 0
10/15/2019 01:45:12 Launching the MT-DNN training
10/15/2019 01:45:12 Loading data/canonical_data/mt_dnn_uncased_lower/mnli_train.json as task 0
Traceback (most recent call last):
  File "train.py", line 432, in <module>
    main()
  File "train.py", line 207, in main
    train_data = BatchGen(BatchGen.load(train_path, True, task_type=task_type, maxlen=args.max_seq_len),
  File "/home/ant/multitask/mt-dnn/mt_dnn/batcher.py", line 53, in load
    with open(path, 'r', encoding='utf-8') as reader:
**FileNotFoundError: [Errno 2] No such file or directory: 'data/canonical_data/mt_dnn_uncased_lower/mnli_train.json'**

where:
ls data
canonical_data  domain_adaptation  MRPC  QQP  SciTail  squad     SST-2  WNLI
CoLA            MNLI               QNLI  RTE  SNLI     squad_v2  STS-B

**Comment by namisan** [comment]
you need to specify data dir by using --data_dir.
