### ISSUE TITLE
Each mini-batch dataset comes from one task?

### ISSUE THREAD

**Issue by ywl0911** [namisan/mt-dnn#106]
hello, I'm a newer. Each mini-batch dataset only coms from one task, right? If not, how to combine the different types of loss.

**Comment by namisan** [comment]
Each task has its own loss during the training.  Saying we have two tasks A/B which are packed as [batch_a, batch_b, batch_b, batch_a], each time we sample a batch, e.g., batch_b, we only compute loss on task b. Not combining is needed.

**Comment by ywl0911** [comment]
Thanks a lot~
