### ISSUE TITLE
No such file or directory: 'ner/ner_train.json'

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#110]
ls ner/
chunk_dev.tsv  chunk_test.tsv  chunk_train.tsv  ner_dev.tsv  ner_test.tsv  ner_train.tsv  pos_dev.tsv  pos_test.tsv  pos_train.tsv  test.txt  train.txt  valid.txt

python3 train.py --data_dir ner/ --init_checkpoint ./mt_dnn_models/bert_model_large_uncased.pt --train_dataset ner --test_dataset ner --task_def experiments/ner/ner_task_def.yml 
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
Namespace(adam_eps=1e-06, answer_att_hidden_size=128, answer_att_type='bilinear', answer_dropout_p=0.1, answer_mem_drop_p=0.1, answer_mem_type=1, answer_merge_opt=1, answer_num_turn=5, answer_opt=0, answer_rnn_type='gru', answer_sum_att_type='bilinear', answer_weight_norm_on=False, batch_size=8, batch_size_eval=8, bert_dropout_p=0.1, bert_l2norm=0.0, cuda=True, data_dir='ner/', data_sort_on=False, dropout_p=0.1, dropout_w=0.0, dump_state_on=False, ema_gamma=0.995, ema_opt=0, embedding_opt=0, encoder_type=<EncoderModelType.BERT: 1>, epochs=5, fp16=False, fp16_opt_level='O1', freeze_layers=-1, global_grad_clipping=1.0, glue_format_on=False, grad_accumulation_step=1, grad_clipping=0, have_lr_scheduler=True, init_checkpoint='./mt_dnn_models/bert_model_large_uncased.pt', init_ratio=1, label_size='3', learning_rate=5e-05, log_file='mt-dnn-train.log', log_per_updates=500, lr_gamma=0.5, max_seq_len=512, mem_cum_type='simple', mix_opt=0, model_ckpt='checkpoints/model_0.pt', momentum=0, mtl_opt=0, multi_gpu_on=False, multi_step_lr='10,20,30', name='farmer', optimizer='adamax', output_dir='checkpoint', ratio=0, resume=False, save_per_updates=10000, save_per_updates_on=False, scheduler_type='ms', seed=2018, task_def='experiments/ner/ner_task_def.yml', tensorboard=False, tensorboard_logdir='tensorboard_logdir', test_datasets=['ner'], train_datasets=['ner'], update_bert_opt=0, vb_dropout=True, warmup=0.1, warmup_schedule='warmup_linear', weight_decay=0)
10/19/2019 12:30:52 0
10/19/2019 12:30:52 Launching the MT-DNN training
10/19/2019 12:30:52 Loading ner/ner_train.json as task 0
Traceback (most recent call last):
  File "train.py", line 434, in <module>
    main()
  File "train.py", line 207, in main
    train_data = BatchGen(BatchGen.load(train_path, True, task_type=task_type, maxlen=args.max_seq_len),
  File "/home/ant/multitask/mt-dnn/mt_dnn/batcher.py", line 53, in load
    with open(path, 'r', encoding='utf-8') as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'ner/ner_train.json'

**Comment by antgr** [comment]
Is it any fault from my part? Thanks

**Comment by antgr** [comment]
@namisan 
a kind reminder

**Comment by antgr** [comment]
There are not json files for NER or pos or chunk. Am I suppose to produce them?
find . -name "*json"
./data/domain_adaptation/snli_001_train.json
./data/domain_adaptation/scitail_train_shuff.json
./data/domain_adaptation/snli_test.json
./data/domain_adaptation/scitail_1_train.json
./data/domain_adaptation/snli_1_train.json
./data/domain_adaptation/snli_5_train.json
./data/domain_adaptation/snli_dev.json
./data/domain_adaptation/scitail_train.json
./data/domain_adaptation/scitail_01_train.json
./data/domain_adaptation/scitail_dev.json
./data/domain_adaptation/snli_train.json
./data/domain_adaptation/scitail_001_train.json
./data/domain_adaptation/snli_train_shuff.json
./data/domain_adaptation/scitail_5_train.json
./data/domain_adaptation/scitail_test.json
./data/domain_adaptation/snli_01_train.json
./data/canonical_data/bert_uncased_lower/qqp_dev.json
./data/canonical_data/bert_uncased_lower/mnli_matched_test.json
./data/canonical_data/bert_uncased_lower/qnli_train.json
./data/canonical_data/bert_uncased_lower/snli_test.json
./data/canonical_data/bert_uncased_lower/sst_dev.json
./data/canonical_data/bert_uncased_lower/wnli_test.json
./data/canonical_data/bert_uncased_lower/sst_test.json
./data/canonical_data/bert_uncased_lower/mnli_train.json
./data/canonical_data/bert_uncased_lower/mrpc_dev.json
./data/canonical_data/bert_uncased_lower/wnli_train.json
./data/canonical_data/bert_uncased_lower/stsb_dev.json
./data/canonical_data/bert_uncased_lower/snli_dev.json
./data/canonical_data/bert_uncased_lower/mnli_mismatched_test.json
./data/canonical_data/bert_uncased_lower/cola_test.json
./data/canonical_data/bert_uncased_lower/scitail_train.json
./data/canonical_data/bert_uncased_lower/qqp_train.json
./data/canonical_data/bert_uncased_lower/rte_test.json
./data/canonical_data/bert_uncased_lower/scitail_dev.json
./data/canonical_data/bert_uncased_lower/cola_dev.json
./data/canonical_data/bert_uncased_lower/snli_train.json
./data/canonical_data/bert_uncased_lower/mrpc_test.json
./data/canonical_data/bert_uncased_lower/mrpc_train.json
./data/canonical_data/bert_uncased_lower/qnli_dev.json
./data/canonical_data/bert_uncased_lower/rte_train.json
./data/canonical_data/bert_uncased_lower/qnli_test.json
./data/canonical_data/bert_uncased_lower/rte_dev.json
./data/canonical_data/bert_uncased_lower/sst_train.json
./data/canonical_data/bert_uncased_lower/cola_train.json
./data/canonical_data/bert_uncased_lower/qqp_test.json
./data/canonical_data/bert_uncased_lower/stsb_train.json
./data/canonical_data/bert_uncased_lower/wnli_dev.json
./data/canonical_data/bert_uncased_lower/mnli_matched_dev.json
./data/canonical_data/bert_uncased_lower/stsb_test.json
./data/canonical_data/bert_uncased_lower/mnli_mismatched_dev.json
./data/canonical_data/bert_uncased_lower/scitail_test.json
./data/canonical_data/data/domain_adaptation/snli_001_train.json
./data/canonical_data/data/domain_adaptation/scitail_train_shuff.json
./data/canonical_data/data/domain_adaptation/snli_test.json
./data/canonical_data/data/domain_adaptation/scitail_1_train.json
./data/canonical_data/data/domain_adaptation/snli_1_train.json
./data/canonical_data/data/domain_adaptation/snli_5_train.json
./data/canonical_data/data/domain_adaptation/snli_dev.json
./data/canonical_data/data/domain_adaptation/scitail_train.json
./data/canonical_data/data/domain_adaptation/scitail_01_train.json
./data/canonical_data/data/domain_adaptation/scitail_dev.json
./data/canonical_data/data/domain_adaptation/snli_train.json
./data/canonical_data/data/domain_adaptation/scitail_001_train.json
./data/canonical_data/data/domain_adaptation/snli_train_shuff.json
./data/canonical_data/data/domain_adaptation/scitail_5_train.json
./data/canonical_data/data/domain_adaptation/scitail_test.json
./data/canonical_data/data/domain_adaptation/snli_01_train.json
./data/canonical_data/data/squad/dev.json
./data/canonical_data/data/squad/train.json
./data/canonical_data/data/squad_v2/dev.json
./data/canonical_data/data/squad_v2/train.json
./data/canonical_data/mt_dnn_models/roberta/encoder.json
./data/squad/dev.json
./data/squad/train.json
./data/squad_v2/dev.json
./data/squad_v2/train.json
./hnn/script/hnn_config_large.json
./sample_data/output/qqp_dev.json
./sample_data/output/mnli_matched_test.json
./sample_data/output/qnli_train.json
./sample_data/output/snli_test.json
./sample_data/output/sst_dev.json
./sample_data/output/wnli_test.json
./sample_data/output/sst_test.json
./sample_data/output/mnli_train.json
./sample_data/output/mrpc_dev.json
./sample_data/output/wnli_train.json
./sample_data/output/stsb_dev.json
./sample_data/output/snli_dev.json
./sample_data/output/mnli_mismatched_test.json
./sample_data/output/cola_test.json
./sample_data/output/scitail_train.json
./sample_data/output/qqp_train.json
./sample_data/output/rte_test.json
./sample_data/output/scitail_dev.json
./sample_data/output/cola_dev.json
./sample_data/output/snli_train.json
./sample_data/output/mrpc_test.json
./sample_data/output/mrpc_train.json
./sample_data/output/qnli_dev.json
./sample_data/output/rte_train.json
./sample_data/output/qnli_test.json
./sample_data/output/rte_dev.json
./sample_data/output/sst_train.json
./sample_data/output/cola_train.json
./sample_data/output/qqp_test.json
./sample_data/output/stsb_train.json
./sample_data/output/wnli_dev.json
./sample_data/output/mnli_matched_dev.json
./sample_data/output/stsb_test.json
./sample_data/output/mnli_mismatched_dev.json
./sample_data/output/scitail_test.json
./sample_data/checkpoint/mnli_mismatched_test_scores_0.json
./sample_data/checkpoint/mnli_matched_dev_scores_0.json
./sample_data/checkpoint/config.json
./sample_data/checkpoint/mnli_mismatched_dev_scores_0.json
./sample_data/checkpoint/mnli_matched_test_scores_0.json
./checkpoint/config.json
./mt_dnn_models/roberta/encoder.json

**Comment by antgr** [comment]
And if I change
-        train_path = os.path.join(data_dir, '{}_train.json'.format(dataset))
+        train_path = os.path.join(data_dir, '{}_train.tsv'.format(dataset))
then
I have:
```
python train.py --data_dir ner/ --init_checkpoint mt_dnn_models/bert_model_base_uncased.pt --train_dataset ner --test_dataset ner --task_def experiments/ner/ner_task_def.yml 
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
Namespace(adam_eps=1e-06, answer_att_hidden_size=128, answer_att_type='bilinear', answer_dropout_p=0.1, answer_mem_drop_p=0.1, answer_mem_type=1, answer_merge_opt=1, answer_num_turn=5, answer_opt=0, answer_rnn_type='gru', answer_sum_att_type='bilinear', answer_weight_norm_on=False, batch_size=8, batch_size_eval=8, bert_dropout_p=0.1, bert_l2norm=0.0, cuda=True, data_dir='ner/', data_sort_on=False, dropout_p=0.1, dropout_w=0.0, dump_state_on=False, ema_gamma=0.995, ema_opt=0, embedding_opt=0, encoder_type=<EncoderModelType.BERT: 1>, epochs=5, fp16=False, fp16_opt_level='O1', freeze_layers=-1, global_grad_clipping=1.0, glue_format_on=False, grad_accumulation_step=1, grad_clipping=0, have_lr_scheduler=True, init_checkpoint='mt_dnn_models/bert_model_base_uncased.pt', init_ratio=1, label_size='3', learning_rate=5e-05, log_file='mt-dnn-train.log', log_per_updates=500, lr_gamma=0.5, max_seq_len=512, mem_cum_type='simple', mix_opt=0, model_ckpt='checkpoints/model_0.pt', momentum=0, mtl_opt=0, multi_gpu_on=False, multi_step_lr='10,20,30', name='farmer', optimizer='adamax', output_dir='checkpoint', ratio=0, resume=False, save_per_updates=10000, save_per_updates_on=False, scheduler_type='ms', seed=2018, task_def='experiments/ner/ner_task_def.yml', tensorboard=False, tensorboard_logdir='tensorboard_logdir', test_datasets=['ner'], train_datasets=['ner'], update_bert_opt=0, vb_dropout=True, warmup=0.1, warmup_schedule='warmup_linear', weight_decay=0)
11/02/2019 11:51:21 0
11/02/2019 11:51:21 Launching the MT-DNN training
dataset:  ner
prefix:  ner
prefix:  ner
task_defs.n_class_map:  {'ner': 12, 'pos': 49, 'chunk': 23}
11/02/2019 11:51:21 Loading ner/ner_train.tsv as task 0
train_path:  ner/ner_train.tsv
task_type:  TaskType.SeqenceLabeling
args.max_seq_len:  512
path:  ner/ner_train.tsv
line:  0	['I-ORG', 'O', 'I-MISC', 'O', 'O', 'O', 'I-MISC', 'O', 'O']	['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.']

Traceback (most recent call last):
  File "train.py", line 441, in <module>
    main()
  File "train.py", line 214, in main
    train_data = BatchGen(BatchGen.load(train_path, True, task_type=task_type, maxlen=args.max_seq_len),
  File "/home/ant/multitask/mt-dnn/mt_dnn/batcher.py", line 59, in load
    sample = json.loads(line)
  File "/home/ant/anaconda3/envs/mt-dnn/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ant/anaconda3/envs/mt-dnn/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

```

**Comment by antgr** [comment]
Also, I tried to run prepro_std.py,
but I think that it does not support sequence tasks:
ValueError: DataFormat.Seqence

python prepro_std.py --model bert-base-uncased --root_dir ner --task_def experiments/ner/ner_task_def.yml 
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
11/04/2019 09:31:52 Task ner
data_format:  DataFormat.Seqence
Traceback (most recent call last):
  File "prepro_std.py", line 551, in <module>
    main(args)
  File "prepro_std.py", line 536, in main
    label_mapper)
  File "prepro_std.py", line 433, in load_data
    raise ValueError(data_format)
ValueError: DataFormat.Seqence

**Comment by antgr** [comment]
So, I added the case ``` or data_format == DataFormat.Seqence ``` to have the same handling as premise:
```
+    import ast
     for line in open(file_path, encoding="utf-8"):
         fields = line.strip("\n").split("\t")
-        if data_format == DataFormat.PremiseOnly:
+        if data_format == DataFormat.PremiseOnly or data_format == DataFormat.Seqence:
             assert len(fields) == 3
-            row = {"uid": fields[0], "label": fields[1], "premise": fields[2]}
+            lab = ast.literal_eval(fields[1])
+            prem = ast.literal_eval(fields[2])
+            assert (len(lab) == len(prem))
+            row = {"uid": fields[0], "label": lab, "premise": prem }
```
then, I ran,
```python prepro_std.py --model bert-base-uncased --root_dir ner --task_def experiments/ner/ner_task_def.yml```
and the ner_train.json was created.
Here are its first lines:
```
0	['I-ORG', 'O', 'I-MISC', 'O', 'O', 'O', 'I-MISC', 'O', 'O']	['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.']
1	['I-PER', 'I-PER']	['Peter', 'Blackburn']
2	['I-LOC', 'O']	['BRUSSELS', '1996-08-22']
3	['O', 'I-ORG', 'I-ORG', 'O', 'O', 'O', 'O', 'O', 'O', 'I-MISC', 'O', 'O', 'O', 'O', 'O', 'I-MISC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']	['The', 'European', 'Commission', 'said', 'on', 'Thursday', 'it', 'disagreed', 'with', 'German', 'advice', 'to', 'consumers', 'to', 'shun', 'British', 'lamb', 'until', 'scientists', 'determine', 'whether', 'mad', 'cow', 'disease', 'can', 'be', 'transmitted', 'to', 'sheep', '.']
```
I ran
```python train.py --data_dir ner/bert_uncased/ --init_checkpoint mt_dnn_models/bert_model_base_uncased.pt --train_dataset ner --test_dataset ner --task_def experiments/ner/ner_task_def.yml```
and a new error occurs:
```
12/12/2019 11:17:26 Total number of params: 109491468
12/12/2019 11:17:26 At epoch 0
Traceback (most recent call last):
  File "train.py", line 434, in <module>
    main()
  File "train.py", line 368, in main
    batch_meta, batch_data = next(all_iters[task_id])
  File "/home/polykratis/mt-dnn/mt_dnn/batcher.py", line 149, in __iter__
    tlab[i, : ll] = torch.LongTensor(label)
TypeError: an integer is required (got type str)
```
I changed symbols ``` 'I-ORG', 'O', etc ``` with numbers (using sed and substitute),
but this leads to gpu error (assert trigger).

Still need help with that.

**Comment by antgr** [comment]
Any one user of the library has implemented this, please contact me, and share how you did it if you want.

**Comment by namisan** [comment]
you need to give ner data.

**Comment by antgr** [comment]
You are wrong. Show a running example
