### ISSUE TITLE
run_mt_dnn.sh

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#112]
I think that script run_mt_dnn.sh has updated paths,
but script run_rte.sh is not
``` MODEL_ROOT="checkpoints"
BERT_PATH="mt_dnn_models/bert_model_large_uncased.pt"
DATA_DIR="data/canonical_data/bert_uncased_lower"

BERT_PATH="../mt_dnn_models/mt_dnn_large_uncased.pt"
DATA_DIR="../data/mt_dnn_uncased_lower"  ```

with git blame:
```
eed674f7  2019-06-20 09:10:04 -0700 16) BERT_PATH="../mt_dnn_models/mt_dnn_large_uncased.pt"
eed674f7  2019-06-20 09:10:04 -0700 17) DATA_DIR="../data/mt_dnn_uncased_lower"
```
```
9eba7eb8     2019-10-16 20:22:30 +0000 16) BERT_PATH="mt_dnn_models/bert_model_large_uncased.pt"
9eba7eb8    2019-10-16 20:22:30 +0000 17) DATA_DIR="data/canonical_data/bert_uncased_lower" ```

**Comment by namisan** [comment]
You need to specify your data_dir.
