### ISSUE TITLE
question for checkpoints

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#113]
Can I use instead of bert, your final model as initial point of training?

**Comment by antgr** [comment]
To answer my own question, yes.
In script download.sh, there is the following line which downloads and saves as mt_dnn_base_uncased.pt the pretrained model. (Correct me if I am wrong).
But even the small pretrained needs a big gpu memory.
``` wget https://mrc.blob.core.windows.net/mt-dnn-model/mt_dnn_base.pt -O "${BERT_DIR}/mt_dnn_base_uncased.pt" ```
If you confirm my understanding lets close it. Thanks

**Comment by namisan** [comment]
yes, you can.
