### ISSUE TITLE
warning during training mt-dnn

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#115]
I followed instruction for  < GLUE Result reproduce   MTL refinement >

I had the following warning:
``` model.py:210: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size. ```

Can you provide more feedback? Should I ignore it? Should I check something?

**Comment by namisan** [comment]
It seems fine.
