### ISSUE TITLE
Mixing experiments using tasks from different folders

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#116]
Hi,
you have three folders,
```  glue  ner squad ```
where in each one you have an .yml file, containing tasks.
We can train all tasks for a yaml file, jointly. But could I train jointly a task of one folder with a task of another folder?  An example is to train 
``` mnli ``` from glue_task_def.yml in glue/, with ``` ner ``` from ner_task_def.yml in ner/
(or specifically for my case, a different sequence labeling task instead of ner)

Is this supported?  Could you guide me on that? 
Thanks a lot!

**Comment by phosseini** [comment]
This is my question too and basically one of the reasons I initially decided to give MT-DNN a try. I wonder if this is supported? For example, can I fine-tune MT-DNN with any of the LMs as the shared layer (e.g. BERT, RoBERTa, etc) on tasks from different folders such as `glue` and `squad`?
@antgr did you find an answer to your question already?

**Comment by antgr** [comment]
Hi @phosseini 
yes I found an answer by myself. I do not know why the issue was closed though.
Anyway.. There are .yml files, for each folder. For example:
https://github.com/namisan/mt-dnn/blob/master/experiments/glue/glue_task_def.yml
or
https://github.com/namisan/mt-dnn/blob/master/experiments/ner/ner_task_def.yml

You can copy paste definitions from one .yml to another, and in that way to add a new task in your availlable tasks for training etc.

Is my explanation clear? Do you need further clarifications?

**Comment by antgr** [comment]
@namisan  what is your opinion?

**Comment by phosseini** [comment]
@antgr thanks, it worked. The only thing is that I also added the following lines to the `run_mt_dnn.sh` to make it work for the tasks I selected:
```
TASK_DEF="all_task_def.yml"
--task_def ${TASK_DEF}
python train.py --data_dir ${DATA_DIR} --task_def ${TASK_DEF} .....
```
where `all_task_def.yml` is the file with the copy-pasted definitions of my selected tasks.
