### ISSUE TITLE
installing fairseq 0.8 in mac osx mojave

### ISSUE THREAD

**Issue by mithunpaul08** [namisan/mt-dnn#122]
Hey guys,

I couldn't find this issue in the issues list (closed or open), hence raising a new one. Kindly pardon if it is duplicate

Issue: When i do `pip install -r requirements.txt` my installation errors out on fairseq0.8 
[stacktrace](https://pastebin.com/20042YEk). can you please tell me

Qn)  If anyone else had this issue while on mac osx mojave and an anaconda environment? 

Qn) or if this might be something am doing wrong/ specific to my OS?

Qn) what machines do you/people train/test your code on usually? I can switch to an ubuntu based machine if needed, hence asking.

Thank you all in advance,
mithun

**Comment by namisan** [comment]
I didn't get other report on max os. I don't use this requirements on windows/ubuntu, which just works fine.
