### ISSUE TITLE
pooled_output vs sequence_output

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#123]
Here the last of all_encoder_layers, is called pooled_output
https://github.com/namisan/mt-dnn/blob/f41104fdf299b2748e52e0e65f15ce039f0c484a/mt_dnn/matcher.py#L111
but some lines before, it is called sequence_output, which I think is the right name
https://github.com/namisan/mt-dnn/blob/f41104fdf299b2748e52e0e65f15ce039f0c484a/mt_dnn/matcher.py#L98

I believe so, due to the following
https://github.com/namisan/mt-dnn/blob/f41104fdf299b2748e52e0e65f15ce039f0c484a/mt_dnn/matcher.py#L97

This caused some confusion to me, and still, I am not pretty sure. Can you clarify?

edit: also ``` elif task_type == TaskType.SeqenceLabeling: ``` case will not play for the case of
```if self.encoder_type == EncoderModelType.ROBERTA:``` , because ```all_encoder_layers``` is only declared in the ```else``` (not roberta).

**Comment by jpilaul** [comment]
I agree. It would be great if we get a comment on this one. That part of the code seemed odd to me.

**Comment by namisan** [comment]
We are working on a new version with better refactors and document.
