### ISSUE TITLE
Clarification of reported number in SMART paper

### ISSUE THREAD

**Issue by ngoyal2707** [namisan/mt-dnn#126]
Hey, 
Great work on the SMART paper. 
I have a very quick questions about numbers reported in Table 2 of the paper.

1) Is `RTE` model on the last row of table 2, initialized from `MNLI` checkpoint or just from `RoBERTa`?

2) Are the reported numbers, mean/ median / best across seeds? If so, how many seeds?

Thanks,
Naman

**Comment by namisan** [comment]
1. It is BERT/RoBERTa, please refer SMART vs MT-DNN section in the paper. The distribution of dev/test of RTE is different. I suggest to monitor MNLI.  
2. I ran 3 models and select the best.

**Comment by ngoyal2707** [comment]
@namisan Thanks for replying.

1) So the number `92%` is without the "Stilt" approach where the model is first trained on MNLI and then RTE, is that correct?

2) if you don't mind, I would suggest, either putting that detail in the paper or using median of 3 (or 5 ) seeds to keep the comparison fair to RoBERTa, freelb and other methods. These tasks can have variance is there accuracy as shown by freeLB paper.

**Comment by namisan** [comment]
I guess comparison is fair. We also picked the best performance among 3 baseline runs in the table as in the table.
