### ISSUE TITLE
Why F1-score 82.7% in paper, but 87.6% in glue benchmark？

### ISSUE THREAD

**Issue by littlepan0413** [namisan/mt-dnn#128]
Why is there such a big improvement? 
What is the difference?

**Comment by namisan** [comment]
Please refer our paper for details.
Xiaodong Liu*, Pengcheng He*, Weizhu Chen and Jianfeng Gao
Multi-Task Deep Neural Networks for Natural Language Understanding
ACL 2019
*: Equal contribution

Xiaodong Liu, Pengcheng He, Weizhu Chen and Jianfeng Gao
Improving Multi-Task Deep Neural Networks via Knowledge Distillation for Natural Language Understanding
arXiv version

Pengcheng He, Xiaodong Liu, Weizhu Chen and Jianfeng Gao
Hybrid Neural Network Model for Commonsense Reasoning
arXiv version
