### ISSUE TITLE
`--multi_gpu_on` not working

### ISSUE THREAD

**Issue by ZhaofengWu** [namisan/mt-dnn#13]
I specified `--multi_gpu_on` and set `CUDA_VISIBLE_DEVICES` to multiple devices, but it looks like only one GPU is used? Why is that?

**Comment by ZhaofengWu** [comment]
Shouldn't
```
parser.add_argument('--multi_gpu_on', action='store_false')
```
be 
```
parser.add_argument('--multi_gpu_on', action='store_true')
```
?

**Comment by namisan** [comment]
yes, it is. It a code cleaning bug...
