### ISSUE TITLE
test: {"metrics": {}, "predictions": <== metrics is empty

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#135]
In `checkpoints` folder, I see that for the test set, there is no result for `metrics` field. 
Compare this to dev set, which is ok e.g {"metrics": {"ACC": 76.69902912621359}

**Comment by Naryxus** [comment]
Hi,

I had the same problem. If I remember right, adding "with_label=True" to the eval_model()-function solved it. Because in inference.py, where the eval_model() function is defined, the code calculates the metrics only, if with_label == True.

**Comment by antgr** [comment]
Thank you!

**Comment by antgr** [comment]
But I see that it is already True.
``` def eval_model(model, data, metric_meta, use_cuda=True, with_label=True, label_mapper=None, task_type=TaskType.Classification):
```

**Comment by namisan** [comment]
For test set, it is set to false. You need to turn it on.

**Comment by antgr** [comment]
Ok thanks. 
Do you mean in mt-dnn/predict.py ?
```
    if args.with_label:
        print(test_metrics)
```
Is there any possibility to take the test results, after the model has already ran? I have a lot of logs, for experiments that ran, and I would like to extract the test results as well.

@namisan should I rerun them?
