### ISSUE TITLE
mlm dataset

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#136]
Do you have a specific mlm dataset? Will you update the download.sh?

**Comment by namisan** [comment]
I tested it on wikipedia. I'm not sure if there is a copyright issue.

**Comment by antgr** [comment]
Thanks! I will look it up.
from the example here (from ```input_examples/mlm_train.json```) which fields are mandatory?
{"id": "316", "url": "...", "title": "...", "text": "..."}
