### ISSUE TITLE
Shared task-specific heads

### ISSUE THREAD

**Issue by chu-tianxiang** [namisan/mt-dnn#14]
When mtl_opt is on (by default), do all GLUE tasks with the same n_class share the same task-specific classifier? Intuitively this seems a little strange that as distinct tasks as SST and QQP use the same classifier.
Another question is, answer_opt is set to 0 in all scripts, so when does SAN apply?
Thank you.

**Comment by namisan** [comment]
Thanks for pointing it out. It is a code cleaning bug. We'll fix it soon.

**Comment by namisan** [comment]
It has options to share the same output layer, however, it is restricted to the same type of tasks which same number of labels. During MT-DNN training, we use SAN.
