### ISSUE TITLE
qnli ranking problem

### ISSUE THREAD

**Issue by YangYang317** [namisan/mt-dnn#144]
1. Which function does g in Equation 5 represent?
2. In table 3, why is ST-DNN has no results on dataset QNLI(v2) ? And why is MT-DNN has results on  QNLI(v2) ?  
3. Is the sample_data for qnli classification task? I didn't see any ranking sample data. 
Thanks for answering the questions.

**Comment by namisan** [comment]
1. g is a linear function. 
2. v2 is not out in first version of paper. We report the mt-dnn result since it  is asked by the glue team. 
3. I'm not sure if I can share the expired data. You may contact GLUE team for the data.
