### ISSUE TITLE
unexpected keyword in Collater

### ISSUE THREAD

**Issue by Vincentwei1021** [namisan/mt-dnn#146]
When running the extractor.py with the command 
python extractor.py --do_lower_case --finput input_examples/pair-input.txt --foutput input_examples/pair-output.json --bert_model bert-base-uncased --checkpoint mt_dnn_models/mt_dnn_base.pt 

I got Traceback (most recent call last):
  File "extractor.py", line 248, in <module>
    main()
  File "extractor.py", line 198, in main
    collater = Collater(gpu=args.cuda, is_train=False, data_type=data_type)
TypeError: __init__() got an unexpected keyword argument 'gpu'

Please help to advise, thanks!

**Comment by namisan** [comment]
Fixed the bug.
thanks,
-xiaodong
