### ISSUE TITLE
Is the code of "SMART: Robust and Efficient Fine-Tuning for Pre-trained Natural Language Models through Principled Regularized Optimization" integrated in this repo?

### ISSUE THREAD

**Issue by qweer28** [namisan/mt-dnn#147]
Hi,

Based on  `update` function in `mt_dnn/model.py`, I do not find the code snippet related to the optimization techniques introduced in the "SMART" paper. 

Could you please point out the related code in this repo? 

Thanks!

**Comment by namisan** [comment]
The paper is under reviewing and we cannot release it due to the conference policy.

**Comment by boubakerwa** [comment]
Hello :)
Any news about this?
