### ISSUE TITLE
Tokenization

### ISSUE THREAD

**Issue by ZhaofengWu** [namisan/mt-dnn#15]
`prepro.py` uses the tokenizer for `bert-base-uncased`. Then if we use a large model and/or an uncased model, would there be inconsistencies?

**Comment by ZhaofengWu** [comment]
On a related note, since tokenzation happens in `prepro.py`, is downloading the `vocab.txt` to `${BERT_DIR}` in `download.sh` useful at all? `prepro.py` uses the `bert-base-uncased` model instead of the local model, so I think the local `vocab.txt` isn't being used.

**Comment by namisan** [comment]
I guess the vocab for bert-base-uncased and bert-large-uncased is same. You may remove vocab.txt here.

**Comment by ZhaofengWu** [comment]
What about casing though? I believe the tokenization schemes for cased vs. uncased are different.

**Comment by ZhaofengWu** [comment]
And to confirm, are the released `mt_dnn_base.pt` and `mt_dnn_large.pt` models cased or uncased?

**Comment by namisan** [comment]
It is uncased.
