### ISSUE TITLE
Prediction fails with new version of Collater

### ISSUE THREAD

**Issue by mariamedp** [namisan/mt-dnn#152]
When trying to execute prediction.py it fails with the following error:

```
File "mtdnn/predict.py", line 69, in main
    data_type=data_type, encoder_type=encoder_type)
TypeError: __init__() got an unexpected keyword argument 'gpu'
```

because the call to mt_dnn.batcher.Collater creator is still using the old required arguments (as it happened with #146)

**Comment by namisan** [comment]
Thanks, I'll review the code.
xiaodong
