### ISSUE TITLE
evaluation of a model

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#156]
Hi,
if we run for example for four epochs training, how should I evaluate the performance of the model? I have the predictions of the model at the end of each epoch, for validation and for test set. What should I report as *the* performance of the model? Should I report the best  performance of the four epochs? Should I report the test set performance for the epoch where the model has the best performance on validation test? Does the framework reports automatically the performance of the model?

**Comment by namisan** [comment]
Regarding evaluation and how to report results, it depends uses need. Basically, we select model on dev and report a final result on test. But it is beyond the scope of this tool.
