### ISSUE TITLE
Wrong tensor size of premise_masks 

### ISSUE THREAD

**Issue by h-sugi** [namisan/mt-dnn#157]
Hi, 
When I run the run_mt_dnn.sh, I had the following error.

> 
>   File "/path/mt-dnn/module/similarity.py", line 350, in forward
>     xWy.data.masked_fill_(x_mask.data, -float('inf'))
> RuntimeError: The expanded size of the tensor (59) must match the existing size (28) at non-singleton dimension 1.  Target sizes: [16, 59].  Tensor sizes: [16, 28]

I found that premise_masks in batcher.py seemed to have wrong vector size.

`premise_masks = torch.ByteTensor(batch_size, premise_len).fill_(1)`

at line 363 in batcher.py should be

`premise_masks = torch.ByteTensor(batch_size, tok_len).fill_(1)`?

**Comment by phosseini** [comment]
Same problem. Changing `premise_len` to `tok_len` is apparently working, not sure that is the right way of doing it though.

**Comment by ruleGreen** [comment]
I encountered this problem too, and fix this according to the answer, another bug appears.

![image](https://user-images.githubusercontent.com/26263128/78623128-90180e80-78b9-11ea-83dd-4e3e4f57c2d7.png)

**Comment by namisan** [comment]
thanks, fixed the bug.
