### ISSUE TITLE
Which mt-dnn variation is implemented on github?

### ISSUE THREAD

**Issue by jubs12** [namisan/mt-dnn#159]
Specifically on this commit f444fe9109d5a9980c9d825a24576c8d873bdf33 (21 days ago), which version of mt-dnn is implemented? So that I can cite it.

**Comment by namisan** [comment]
Thanks @jubs12 
The new features are in here: https://arxiv.org/abs/2002.07972

**Comment by jubs12** [comment]
Thanks. So, adversarial training is implemented on it?

**Comment by namisan** [comment]
Please refer the script: https://github.com/namisan/mt-dnn/blob/master/scripts/run_mt_dnn.sh
