### ISSUE TITLE
Why using "ratio" argument?

### ISSUE THREAD

**Issue by svboeing** [namisan/mt-dnn#16]
If "ratio" argument is provided, then in each epoch only `random_picks=min(len(MNLI task batches) * args.ratio, len(all other tasks batches))` from `len(all other tasks batches)` are used, instead of using all other tasks batches. Such behavior seems strange to me, considering the fact that MNLI has most examples throughout the GLUE dataset. Could you please explain, what is the benefit of not using some of the examples from smaller datasets on each epoch?
Thank you very much.

**Comment by namisan** [comment]
We implemented several variants of MTL training. The ratio is from our NAACL19 paper, attached https://arxiv.org/pdf/1809.06963.pdf.  You can try it on a specific task, which may give some improvement.

**Comment by v1nc3nt27** [comment]
So, the purpose of the ratio parameter is, given one enormous dataset and some smaller ones, you can reduce the bigger one's impact, thus preventing it to  dominate the learning process?
Also, I was wondering; if you do not use the ratio parameter, you will actually train on ALL datasets, is that correct? It's not that some of the smaller ones might get dropped and you end up only training on the big ones?

**Comment by namisan** [comment]
@svboeing ratio only cares about the first tasks and treats other tasks as additional tasks for performance boost. Please refer our NAACL paper for details.
