### ISSUE TITLE
Support for general QA

### ISSUE THREAD

**Issue by jubs12** [namisan/mt-dnn#160]
Does mt-dnn support a general question-answering task? Given a question and multiple answers?

**Comment by namisan** [comment]
You can formulate it as a ranking task, which is supported by the current toolkit. If you want a SQuAD-like multi-spans, the current version dose not support yet.
I'm currently working on covid-19 data processing as volunteer and expect a longer time for the required feature.

**Comment by namisan** [comment]
Please see the updated version.
