### ISSUE TITLE
loss vs kd_loss

### ISSUE THREAD

**Issue by antgr** [namisan/mt-dnn#167]
What is loss and what is kd_loss ?

example:
-------------------------------------------
mnli:
  data_format: PremiseAndOneHypothesis
  encoder_type: BERT
  dropout_p: 0.3
  enable_san: true
  labels:
  - contradiction
  - neutral
  - entailment
  metric_meta:
  - ACC
  loss: CeCriterion <============
  kd_loss: MseCriterion <==============
  n_class: 3
  split_names:
  - train
  - matched_dev
  - mismatched_dev
  - matched_test
  - mismatched_test
  task_type: Classification

**Comment by namisan** [comment]
It is used for knowledge distillation, seeing our paper in readme.
