### ISSUE TITLE
Anyone use XLNET encounter "Can not set attribute"

### ISSUE THREAD

**Issue by ruleGreen** [namisan/mt-dnn#168]
![image](https://user-images.githubusercontent.com/26263128/79946367-6a3a5e80-84a2-11ea-861b-fe901644a80a.png)

**Comment by ruleGreen** [comment]
It seems that attributes name of XLNET is not same as BERT or other models.

**Comment by namisan** [comment]
Regarding xlnet, we didn't find it is better than roberta in many tasks. I'll continue to test and will consider whether it will support it.

**Comment by ruleGreen** [comment]
@namisan ok, thank u for your information, I just want to compare the performance of xlnet and roberta, thank u again.
