### ISSUE TITLE
Demo tool

### ISSUE THREAD

**Issue by rudra0713** [namisan/mt-dnn#17]
Hi,
   Is there any online demo interface for mt-dnn? I am working on a task similar to textual entailment and I would like to see how mt-dnn performs on a very small subset of my dataset?

**Comment by namisan** [comment]
Unfortunately, there is no online demo. I don't have time work on this recently.  
You may run the following script to play which should be very fast to test: https://github.com/namisan/mt-dnn/blob/master/scripts/run_rte.sh
