### ISSUE TITLE
error when running the scripts/run_mt_dnn.sh file

### ISSUE THREAD

**Issue by shijing001** [namisan/mt-dnn#175]
I downloaded the codebase and tried to reproduce the results on a linux machine. Here is the bash script:

#!/bin/bash
#SBATCH -e slurm.err
#SBATCH -p carin-gpu --gres=gpu:1
#SBATCH --mem=30G # adjust as needed
#SBATCH -c 2 # adjust as needed
module load Python-GPU/3.6.5

prefix="mt-dnn"
BATCH_SIZE=2
gpu=0
echo "export CUDA_VISIBLE_DEVICES=${gpu}"
export CUDA_VISIBLE_DEVICES=${gpu}
tstr=$(date +"%FT%H%M")

train_datasets="mnli,rte,qqp,qnli,mrpc,sst,cola,stsb"
test_datasets="mnli_matched,mnli_mismatched,rte"
MODEL_ROOT="checkpoints"
BERT_PATH="mt_dnn_models/bert_model_base_uncased.pt"
DATA_DIR="data/canonical_data/bert_uncased_lower"

answer_opt=1
optim="adamax"
grad_clipping=0
global_grad_clipping=1
lr="5e-5"

model_dir="checkpoints/${prefix}_${optim}_answer_opt${answer_opt}_gc${grad_clipping}_ggc${global_grad_clipping}_${tstr}"
log_file="${model_dir}/log.log"
python train.py --data_dir ${DATA_DIR} --init_checkpoint ${BERT_PATH} --batch_size ${BATCH_SIZE} --output_dir ${model_dir} --log_file ${log_file} --answer_opt ${answer_opt} --optimizer ${optim} --train_datasets ${train_datasets} --test_datasets ${test_datasets} --grad_clipping ${grad_clipping} --global_grad_clipping ${global_grad_clipping} --learning_rate ${lr} --grad_accumulation_step 4 --do_lower_case

Here is the error:

CUDA 9.0
Python-GPU 3.6.5
/opt/apps/rhel7/Python-GPU-3.6.5/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:19: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
Traceback (most recent call last):
  File "train.py", line 360, in <module>
    main()
  File "train.py", line 291, in main
    model.update(batch_meta, batch_data)
  File "/work/ss1043/mt-dnn/mt_dnn/model.py", line 168, in update
    logits = self.mnetwork(*inputs)
  File "/opt/apps/rhel7/Python-GPU-3.6.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/ss1043/mt-dnn/mt_dnn/matcher.py", line 131, in forward
    logits = task_obj.train_forward(sequence_output, pooled_output, premise_mask, hyp_mask, decoder_opt, self.dropout_list[task_id], self.scoring_list[task_id])
  File "/work/ss1043/mt-dnn/tasks/__init__.py", line 48, in train_forward
    logits = task_layer(sequence_output, hyp_mem, premise_mask, hyp_mask)
  File "/opt/apps/rhel7/Python-GPU-3.6.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/ss1043/mt-dnn/module/san.py", line 88, in forward
    att_scores = self.attn(x, h0, x_mask)
  File "/opt/apps/rhel7/Python-GPU-3.6.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/ss1043/mt-dnn/module/similarity.py", line 463, in forward
    scores = self.score_func(x1, x2, mask)
  File "/opt/apps/rhel7/Python-GPU-3.6.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/ss1043/mt-dnn/module/similarity.py", line 350, in forward
    xWy.data.masked_fill_(x_mask.data, -float('inf'))
RuntimeError: The expanded size of the tensor (66) must match the existing size (25) at non-singleton dimension 1.  Target sizes: [2, 66].  Tensor sizes: [2, 25]

**Comment by namisan** [comment]
fix it.
