### ISSUE TITLE
SNLI 的数据集太小了，运行很快就结束了

### ISSUE THREAD

**Issue by Sarraup** [namisan/mt-dnn#177]
在运行download.sh之后并没有下载SNLI数据集，我在sample_data中找到了SNLI的样例是train.tsv文件，但是特别小，就一行，所以很快train.py就运行结束了。我想问是否是我的数据集不对，那么SNLI数据集我应该去哪里找呢？如果我只看文本蕴涵的结果，也就是处理SNLI数据集的结果，那我应该怎么做呢？

**Comment by namisan** [comment]
请在这个网站下载：https://nlp.stanford.edu/projects/snli/
