### ISSUE TITLE
why QNLI task not using ranking. 

### ISSUE THREAD

**Issue by luomancs** [namisan/mt-dnn#178]
Hi, 
In this file glue_task_def.yml, the qnli task use PremiseAndOneHypothesis and the loss is CeCriterion. however, in the paper, section 3.1, you said that using relevance ranking is more helpful, given a query Q, we make a list of candidates, where only one of them are positive and the rest are negative. So I think we should use PremiseAndMultipleHypothesis and ranking loss for qnli task, right?

**Comment by namisan** [comment]
The latest GLUE release doesn't support/allow QNLI as ranking. Yes, if you want to use ranking loss, use PremiseAndMultipleHypothesis.

**Comment by luomancs** [comment]
Hi, 

If I want to use rank loss, except for changing the data to PremiseAndMultipleHypothesis format, are there other code I need to change?

Thank you

**Comment by namisan** [comment]
For training, I don't think you need to change any code. Only changing the config file is enough.
For evaluation, you may need to change if you want to compute R@2 or R@10.
