### ISSUE TITLE
Maybe it is a bug in alum?

### ISSUE THREAD

**Issue by colourful-tree** [namisan/mt-dnn#184]
About the Algorithm 1 in paper, https://arxiv.org/pdf/2004.08994.pdf

![image](https://user-images.githubusercontent.com/17588577/91435321-b9e9c600-e898-11ea-8c3e-382f92c98ced.png)

- I think the Gadv is uesd to update the noise? But, i saw that Gadv don't add any noise in the code below

https://github.com/namisan/mt-dnn/blob/99d1b200714327c65ba02e52bd092cacde0dabbe/alum/adv_masked_lm.py#L100

- And the variable adv_direct addad to a embed, which doesn't match the paper i think.
![image](https://user-images.githubusercontent.com/17588577/91436412-a17aab00-e89a-11ea-99b0-5d26cf32bbc4.png)

https://github.com/namisan/mt-dnn/blob/99d1b200714327c65ba02e52bd092cacde0dabbe/alum/adv_masked_lm.py#L101

**Comment by namisan** [comment]
good catch. actually, there is another bug. I haven't have time to fix it yet. will do it after my vacation.

**Comment by RyanHuangNLP** [comment]
@namisan is there any update about the bug?

**Comment by SenYan1999** [comment]
should it be 
```python
newembed = embed + (adv_direct + noise) * self.args.adv_step_size
```

**Comment by SenYan1999** [comment]
Should it be 
```python
adv_direct = self.adv_project(delta_grad + noise, norm_type=self.args.project_norm_type, eps=self.args.noise_gamma)  
```

**Comment by namisan** [comment]
I'll update in the weekend.
