### ISSUE TITLE
Maybe it is a bug in mt_dnn/batcher.py

### ISSUE THREAD

**Issue by shiitake8630** [namisan/mt-dnn#187]
I got an error when I run train.py with pair task and using SAN.
The error was caused by the following error occurred at line 247 in module/batcher.py.

”RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 ‘mask’”

Is there any reason to use ‘BoolTensor’ instead of ‘ByteTensor’ at lines 365-366 in mt_dnn/batcher.py?

**Comment by namisan** [comment]
You can change it to Byte for pytorch < 1.3.0. I update it to Bool to support pytorch >= 1.30.
