### ISSUE TITLE
两个关于模型的问题

### ISSUE THREAD

**Issue by ConanCui** [namisan/mt-dnn#19]
你好
想请教你们两个问题。
    1. multi-task带来的促进应该和task之间的联系有关，什么时候task能够带来好的提升，以至于什么时候task反而会影响对方的表现？有没有一些理论的分析呢？
    2.文章中的多个task的objective function，是否考虑过给他们设置不同的权重呢，比如最终的loss = 权重1*loss1+权重2*loss2....

**Comment by jfgao-microsoft** [comment]
these tasks need to be related in order to help. but we don't have any theoretical justification. And it is a good idea to add weights -- and finetuning the weights might lead to some improvement. We did not do it mainly for simplicity.

**Comment by ConanCui** [comment]
Thanks for your reply
