### ISSUE TITLE
update mt-dnn/download.sh ?

### ISSUE THREAD

**Issue by leewea** [namisan/mt-dnn#197]
`## DOWNLOAD GLUE DATA
## Please refer glue-baseline install requirments or other issues.
git clone https://github.com/nyu-mll/jiant-v1-legacy.git
cd jiant-v1-legacy
python scripts/download_glue_data.py --data_dir $DATA_DIR --tasks all

cd ..
rm -rf jiant-v1-legacy
#########################`

**Comment by namisan** [comment]
@leewea  would you submit a pull request?

**Comment by namisan** [comment]
thanks. done!
