### ISSUE TITLE
The implement of Mean Teacher for SMART

### ISSUE THREAD

**Issue by YeDeming** [namisan/mt-dnn#199]
Hi, 

Thanks for releasing the code.

In the Mean teacher of SMART, The model parameters is updated as theta = (1-beta)*theta_new + beta * theta_old. But I can't find corresponding code. Could you please point out the code?

Thanks!
Best,
Deming

**Comment by namisan** [comment]
The current imp of mean teacher is ugly but functional. Thus, I didn't turn it on and plan to re-imp a better version.  The old version is already in rep, you just need to add a few lines to make it work. Code can be found:  https://github.com/namisan/mt-dnn/blob/master/module/my_optim.py#L8
