### ISSUE TITLE
Any instruction in reproducing MC-TACO result?

### ISSUE THREAD

**Issue by PosoSAgapo** [namisan/mt-dnn#201]
Adversarial Training for Commonsense Inference this paper used mt-dnn framework and I guess that you are in the same lab. It is hard and time consuming to reproduce the result without proper instruction or script. Any plans in updating MC-TACO reuslt reproducing guidance like other datasets in the project home page? Since as I noticed for now , there is no information about MC-TACO dataset.

**Comment by namisan** [comment]
My co-author @lis-kp mainly worked on this. You may contact her for the details and codes
