### ISSUE TITLE
A issue about score_mask

### ISSUE THREAD

**Issue by sfzhou5678** [namisan/mt-dnn#209]
Hi, 
If I unserstand correctly, the code in link below should be "**score_mask[i][j] = 1.0**"? 
https://github.com/namisan/mt-dnn/blob/471f717a25ab744e710591274c3ec098f5f4d0ad/experiments/squad/squad_utils.py#L480

Thanks

**Comment by namisan** [comment]
I have an updated version for QA. Please refer the new version in readme: Question Answer Task.
