### ISSUE TITLE
Using the model in Colab

### ISSUE THREAD

**Issue by vprelovac** [namisan/mt-dnn#210]
I would like to try SMART model in a jupyter notebool a'la Colab with the idea to extract sentence embeddings and use them on my own dataset. Is it possible to bootstrap that with few lines of code similar to for example :

https://tfhub.dev/google/universal-sentence-encoder/4

Thank you!

**Comment by namisan** [comment]
Sorry, I haven't used TF a while and I don't know how to support it.
