### ISSUE TITLE
Posterior Differential Regularization implementation

### ISSUE THREAD

**Issue by shaked571** [namisan/mt-dnn#211]
Hi,
Im looking for the PDR (Posterior Differential Regularization ) implementation and couldnt find it in the repo,
Can you please advice?

**Comment by namisan** [comment]
Please use the losses:
https://github.com/namisan/mt-dnn/blob/471f717a25ab744e710591274c3ec098f5f4d0ad/mt_dnn/loss.py#L147
https://github.com/namisan/mt-dnn/blob/471f717a25ab744e710591274c3ec098f5f4d0ad/mt_dnn/loss.py#L166
