### ISSUE TITLE
UnencryptedCookieSessionFactoryConfig

### ISSUE THREAD

**Issue by prince14322** [namisan/mt-dnn#213]
Once I try to run train.py it gives the below error:
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)

I have installed everything in a new conda env with pip install -r requirements.txt but still getting the above error.

Thanks in advance.

**Comment by prince14322** [comment]
Referred this : 
https://github.com/NVIDIA/apex#quick-start

Finally did this step
Apex also supports a Python-only build (required with Pytorch 0.4) via

pip install -v --disable-pip-version-check --no-cache-dir ./

It is resolved.

**Comment by MilenioScience** [comment]
Is there any expalantion how to install apex NVIDIA in google colab?
