### ISSUE TITLE
How to train ny own dataset with MT-DNN 

### ISSUE THREAD

**Issue by ammaarahmad1999** [namisan/mt-dnn#215]
I have a dataset for 3 tasks in csv file. How to train the model

**Comment by namisan** [comment]
please refer:
prepro data: https://github.com/namisan/mt-dnn/blob/master/tutorials/Run_Your_Own_Task_in_MT-DNN.ipynb
multi-task training: https://github.com/namisan/mt-dnn/blob/master/scripts/run_mt_dnn.sh
