### ISSUE TITLE
Potential bug in predict.py

### ISSUE THREAD

**Issue by chawannut157** [namisan/mt-dnn#216]
In predict.py, it's still using **use_cuda=args.cuda,**  which is no longer used in the eval_model function.

`eval_model(model, test_data,metric_meta=metric_meta,**use_cuda=args.cuda,** with_label=args.with_label)`

In inference.py

`def eval_model(model, data, metric_meta, device, with_label=True, label_mapper=None, task_type=TaskType.Classification):`

**Comment by namisan** [comment]
thanks @chawannut157 , fixed the bug.
