### ISSUE TITLE
How to convert pytorch_model.bin to .pt so that I can fine tune it with your code?

### ISSUE THREAD

**Issue by junwang4** [namisan/mt-dnn#219]
For example, I need to use the pretrained BioBERT model from [https://huggingface.co/dmis-lab/biobert-base-cased-v1.2/tree/main](https://huggingface.co/dmis-lab/biobert-base-cased-v1.2/tree/main). It has 3 files: pytorch_model.bin, vocab.txt, config.json. How should I convert it to your .pt model? Thanks!

**Comment by namisan** [comment]
The format is similar to: https://github.com/namisan/mt-dnn/blob/master/scripts/strip_model.py
I've updated the transformer package. You can just update related files to the pretrained models of interest, e.g.,
https://github.com/namisan/mt-dnn/blob/master/pretrained_models.py
