### ISSUE TITLE
How we can use mt-dnn to do Multi-Label Classification?

### ISSUE THREAD

**Issue by akkefa** [namisan/mt-dnn#226]
@namisan I have tweets dataset with multi-labels.

  | ID | Tweet | anger | anticipation | disgust | fear | joy | love | optimism | pessimism | sadness | surprise | trust
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2018-Ar-00289 | باقي ١٠ دقايق واخلص حلقة سكول الثانيه بس النت ... | 1 | 0 | 1 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0
2018-Ar-02519 | معاناة لما يكون دايماً إحساسك بمحله ..... | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0
2018-Ar-01952 | لو فيه جائزه اكثر موسوسه تخاف من الامراض فزت ب... | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0
2018-Ar-02912 | ما يستفز راحة البال إلا الذكريات ☹️ 💔 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0
2018-Ar-02756 | القلب ياوقت والنفس ماهي مرتاحه ونبض القلب ماهو... | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0

How can I define multi-labels in the task_def.yml file?

**Comment by namisan** [comment]
please refer: https://github.com/namisan/mt-dnn/blob/master/experiments/glue/glue_task_def.yml#L17
