### ISSUE TITLE
Problems with downloading datasets and weights

### ISSUE THREAD

**Issue by Xnhyacinth** [namisan/mt-dnn#252]
https://mrc.blob.core.windows.net/mt-dnn-model/mt_dnn_base.pt
Resolving mrc.blob.core.windows.net (mrc.blob.core.windows.net)... 20.60.1.4
Connecting to mrc.blob.core.windows.net (mrc.blob.core.windows.net)|20.60.1.4|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-06-11 05:04:50 ERROR 409: Public access is not permitted on this storage account..

Show me rejected when downloading partial weights and datasets

**Comment by namisan** [comment]
Here is the new link. 
https://mrc.blob.core.windows.net/mt-dnn-model/mt_dnn_bert_model_base.pt

**Comment by Xnhyacinth** [comment]
ok very thanks！




Xnhyacinth
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "namisan/mt-dnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 上午7:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [namisan/mt-dnn] Problems with downloading datasets and weights (Issue #252)





 
Here is the new link.
 https://mrc.blob.core.windows.net/mt-dnn-model/mt_dnn_bert_model_base.pt
