### ISSUE TITLE
Assertion Error on preprocessing QNLI samples

### ISSUE THREAD

**Issue by ksurya** [namisan/mt-dnn#27]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/932927/57526767-3fd8ab00-72fc-11e9-984d-f8812e39bf19.png">

**Comment by namisan** [comment]
QNNLI denotes that we formulate QNLI as a pair-wise ranking task which is only on the old version. You can use qnli prepossess pipeline in the script.
