### ISSUE TITLE
Multi-gpu training not working

### ISSUE THREAD

**Issue by ZhengtianXu** [namisan/mt-dnn#28]
I'm trying to finetune this model on a specific task. But when I run the example scripts of run_rte.sh, the multi-gpu training is not working when I set CUDA_VISIBLE_DEVICES="0,1,2,3", it seems that only the first gpu is working.

I have only 4 1080 ti gpus, when I run the run_rte.sh script, I can only adjust the batch size to 1 to avoid out of memory, can this be possible training on 1080Ti?

**Comment by cca2016** [comment]
Yes, you are the best. Dai Dai wo, wo yao shang wang zhe
