### ISSUE TITLE
GPU memory usage keeps increasing during training

### ISSUE THREAD

**Issue by slih-sh** [namisan/mt-dnn#29]
I tried to finetune the pretrained mt-dnn model on a specific task, but the GPU memory usage keeps growing. After training for 1000 iterations, the memory is fully occupied, causing 'run out of memory' error. The experiment was conducted on 1080TI.

**Comment by namisan** [comment]
We haven't seen this issue. Can you reduce batch size?

**Comment by slih-sh** [comment]
Yes，reduce batch size can solve this problem，but I wonder why the program crashes after 1000 iterations rather than the beginning.  And I have another problem of reloading the finetuned models. What is the proper way to reload them, just change the bert path to the finetuned model path cannot work.

**Comment by namisan** [comment]
Unlike PyTorch BERT, which uses a fix max length and pads each sample up to e.g. 512 tokens, we use a dynamic batching trick to speed up training and the max length is determined by samples in a min-batch. If  a longer length is met at 1001 iter, the model requires more gpu mem and it'll crash. Regarding reload, you may check the model save part and then load parameters for further usage. Hope this answers your questions.
