### ISSUE TITLE
how to feed data, task sampling or data sampling

### ISSUE THREAD

**Issue by yyht** [namisan/mt-dnn#30]
I had tried to do multitask learning on original BERT for seven Chinese tasks. I tried to feed data with task sampling and data sampling. The results are somehow confusing. When feeding model using task sampling strategy just like MTDNN, the mtl trained model can't achieve better results than single-task-training, But when i apply data sampling, mtl trained model can achieve better results than BERT, EIRNE on lcqmc, chnsenticorp and xnli. Is there any theoritical guidance for mtl on different datasets

**Comment by yyht** [comment]
when i finetune mtl model on single task dataset, the results are not better than mtl trained model

**Comment by namisan** [comment]
Sorry, I didn't get the your questions. What do you mean by task sampling and data sampling?

**Comment by yyht** [comment]
AUTOSEM: Automatic Task Selection and Mixing in Multi-Task Learning
for mtl, i think how to sample data for training is crucial. 
task sampling-----sample mini-batch from sampled task based on the numbers of training samples
data sampling-----sample mini-batch from all tasks with pre-defined mixing ratio

**Comment by namisan** [comment]
Thanks for clarifying these questions. 
These two questions are pretty challenge and good research topics as well. The core issue of MTL is how to schedule tasks and sample data within each task. There is no good theories to guild this. Combing MTL with meta learning may be a good solution, which I am working on now and we can discuss details via emails if you are interested in.
Practically, there are some tricks helping us to get good results. E.g., you may use the idea of data select for a specific task we mainly care about, e.g., SQuAD, as our NAACL paper attached.
https://arxiv.org/pdf/1809.06963.pdf
