### ISSUE TITLE
prepro.py fails with assert len(lines) %2 == 0

### ISSUE THREAD

**Issue by eisber** [namisan/mt-dnn#36]
I'm on commit 25c3bd1cfee2db14c7e8dbec4a369acaa95b15f6

05/27/2019 03:38:53 Loaded 5463 QNLI test samples
Traceback (most recent call last):
  File "prepro.py", line 352, in <module>
    main(args)
  File "prepro.py", line 193, in main
    qnnli_train_data = load_qnnli(qnli_train_path, GLOBAL_MAP['qnli'])
  File "/home/markus/mt-dnn/data_utils/glue_utils.py", line 113, in load_qnnli
    assert len(lines) % 2 == 0
AssertionError

**Comment by ankmathur96** [comment]
same error - commenting to see if there's a followup

**Comment by ankmathur96** [comment]
As an initial diagnosis, it seems that the QNNLI loader is loading the QNLI file, which has 104744 lines including the header. We remove the header, leaving an odd number of lines which fails the assert. This is true for the dev and test set files as well, which have 5464 lines.

I'm not familiar with what data is supposed to be read in, but it seems only 1 of the pairs of lines in the QNLI data actually don't trigger the if statement [here](https://github.com/namisan/mt-dnn/blob/master/data_utils/glue_utils.py#L119). Not sure if that's expected, but seemed weird. 

I tried dropping the assert and breaking if there's no subsequent line (if idx+1 >= len(lines)), but that fails on the test set on the assertion [here](https://github.com/namisan/mt-dnn/blob/master/data_utils/glue_utils.py#L122). I tried adding code that simply continues the loop if block1[1] != block2[1].

That code is still running, but it's possible the preprocessing breaking might screw up later stages of the model and might make fine-tuning worse? @namisan please let us know if there's a stable commit that doesn't experience this problem

**Comment by namisan** [comment]
Thanks for suggestions. I've fixed the issue and refer README for more information.

**Comment by ankmathur96** [comment]
Confirmed this works - thanks @namisan!
