### ISSUE TITLE
How to Improve Performance on WNLI

### ISSUE THREAD

**Issue by senseandcalm** [namisan/mt-dnn#38]
I just noticed that the performance on WNLI have got a huge improvement! That's really marvelous. Can't wait to know more details about it.

**Comment by namisan** [comment]
We use data augmentation tricks as: https://arxiv.org/pdf/1905.06290.pdf

**Comment by ngoyal2707** [comment]
@namisan could you give more details? Specifically following questions:

1) Is the WNLI submission still first multi tasked trained using all 10 (including WNLI) tasks and then finetuned on WNLI?

2) Did you form the task as masked prediction task as above paper states and finetuned `Bert` on WSCR and MaskedWikiDataset with masked prediction?
