### ISSUE TITLE
Apply the architecture to individual task

### ISSUE THREAD

**Issue by guanqun-yang** [namisan/mt-dnn#39]
Hi,

I am now working on a sentiment analysis task and found that this architecture might be a good choice for my application.

However, I am quite confused on how to use this architecture on my custom data. More specifically,
if I would like to **directly** apply this architecture to my custom data. What I should do? Is there a more detailed tutorial for the use of the architecture?

**Comment by namisan** [comment]
We'll write a tutorial for this soon.

**Comment by ilivans** [comment]
What do you mean by direct "application"? Fine-tuning?

**Comment by guanqun-yang** [comment]
> We'll write a tutorial for this soon.

**Comment by guanqun-yang** [comment]
> What do you mean by direct "application"? Fine-tuning?

Yes. And it would be great this whole repo could be better documented. At current stage I could basically read the original code and guess what each code snippet's functionality.

**Comment by Rajratnpranesh** [comment]
> Hi,
> 
> I am now working on a sentiment analysis task and found that this architecture might be a good choice for my application.
> 
> However, I am quite confused on how to use this architecture on my custom data. More specifically,
> if I would like to **directly** apply this architecture to my custom data. What I should do? Is there a more detailed tutorial for the use of the architecture?

**_Did you found the way to run specific task on mt-dnn. For example if I just want to run single sentence classification task on CoLa dataset. Please help.
Thank You_**
