### ISSUE TITLE
can you share the chinese model

### ISSUE THREAD

**Issue by terrifyzhao** [namisan/mt-dnn#44]

**Comment by namisan** [comment]
Will convert the Chinese model soon.

**Comment by namisan** [comment]
wget https://mrc.blob.core.windows.net/mt-dnn-model/bert_base_chinese.pt 

Note that it is converted from Google's BERT model: https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip

**Comment by fanfanba** [comment]
> wget https://mrc.blob.core.windows.net/mt-dnn-model/bert_base_chinese.pt
> 
> Note that it is converted from Google's BERT model: https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip

Hi namisan. How do you convert bert model to yours ? I am very insteresting in that. Can you share your covert method. Thank you very much.

**Comment by namisan** [comment]
See the instruction of readme.

**Comment by OYE93** [comment]
Hi @namisan, I have some questions about how to use the Chinese bert model, 
1. this bert model is not fine tuned ?
2. if I want to use this model in my classification task, I have to train it on mt-dnn, then fine-tuning the trained model, am I right? Thanks a lot
