### ISSUE TITLE
MT-DNN tutorial and knowledge distillation

### ISSUE THREAD

**Issue by dchang56** [namisan/mt-dnn#48]
Hello,

Do you have a rough timeline for when you might release:
1. a tutorial for using pre-trained MT-DNN models,
2. code/models for MT-DNN with knowledge distillation?

Thank you!

**Comment by namisan** [comment]
We plan to release KD related code/model within one/two weeks. Regarding 1, you may refer MT-DNN training pipeline/finue-tuning pipeline. I may add an additional section and explain how to build a new task on top of MT-DNN.
