### ISSUE TITLE
Changes to made for training for a specific purpose.

### ISSUE THREAD

**Issue by vikas-baghel** [namisan/mt-dnn#49]
What are the changes we have to make in the tran.py file  in order to train for specific purpose(STSB). Some of the changes I have made are following:-
1.  train_dataset=stsb
2.  test_dataset=stsb
Apart from that is there anything else I need to change because right now I am getting all predictions as 0.
Even the run_stsb.sh is giving all zero prediction instead of predicting similarity score between 0 and 5.
Please help!!!!

**Comment by namisan** [comment]
Please follow the glue example in the experiments.

**Comment by Rajratnpranesh** [comment]
> What are the changes we have to make in the tran.py file in order to train for specific purpose(STSB). Some of the changes I have made are following:-
> 
> 1. train_dataset=stsb
> 2. test_dataset=stsb
>    Apart from that is there anything else I need to change because right now I am getting all predictions as 0.
>    Even the run_stsb.sh is giving all zero prediction instead of predicting similarity score between 0 and 5.
>    Please help!!!!

**Hey Vikas,

I am working on the mt-dnn repo. Did you found a  way to run the training for a specific task?
Please reply ASAP. I need your help.
thank You**
