### ISSUE TITLE
Clarification on reported numbers between leaderboard vs latest paper on arxiv

### ISSUE THREAD

**Issue by ngoyal2707** [namisan/mt-dnn#50]
Hi, I have couple of questions about the test set numbers, can you please clarify:

1) What's the test set number of original single MT-DNN model (non KD)? The paper says it's `82.7` vs leaderboard says `85.1`? The difference seems more than just WNLI.

2) What's the difference between MTDNN-KD vs MTDNN-ensemble in Table 3 in https://arxiv.org/pdf/1904.09482.pdf paper.

**Comment by namisan** [comment]
Please see the answers as follows.
1. MT-DNN: 82.x and MT-DNN-KD: 85.x as in the paper. 
2. MT-DNN-ensemble is the ensemble result of a bunch of MT-DNN models as in sec 4.1. Basically, I trained several MT-DNN models with different dropout and cased/uncased, and merge the prediction scores. MT-DNN-KD is trained with both soft-labels, generated by MT-DNN-ensemble, and hard label (human annotated). Note that MT-DNN-KD is a single model.

**Comment by ngoyal2707** [comment]
Thanks for the clarification.
