### ISSUE TITLE
How do you convert tf bert model to pt file? Can you share your covert method. Thank you very much.

### ISSUE THREAD

**Issue by fanfanba** [namisan/mt-dnn#52]
wget https://mrc.blob.core.windows.net/mt-dnn-model/bert_base_chinese.pt

Note that it is converted from Google's BERT model: https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip

Hi namisan. How do you convert bert model to yours ? I am very insteresting in that. Can you share your covert method. Thank you very much.

**Comment by namisan** [comment]
Please follow instruction: Convert Tensorflow BERT model to the MT-DNN format in readme.
