### ISSUE TITLE
Can't resume training the model

### ISSUE THREAD

**Issue by LouYJ** [namisan/mt-dnn#53]
When the procedure is interrupted accidentally. I want to resume the training procedure with the checkpoint in `checkpoints/model_*.pt`. But I don't know why it comes out some error:

Traceback (most recent call last):
  File "../train.py", line 352, in <module>
    main()
  File "../train.py", line 314, in main
    model.update(batch_meta, batch_data)
  File "/home/mt-dnn/mt_dnn/model.py", line 171, in update
    self.optimizer.step()
  File "/home/mt-dnn/module/bert_optim.py", line 120, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #4 'other'

I didn't change any other code but just hyperparameters. How to deal with such a problem?

**Comment by namisan** [comment]
I didn't know how you resume your checkpoint. The error says that you need to copy your model into _GPU_. One is on CPU and the other one on GPU.

**Comment by LouYJ** [comment]
In my way, I use the checkpoint I stored during the last training to instead the `init_checkpoint`. I didn't change other parameters. I don't know why the model is not on the GPU.

**Comment by namisan** [comment]
I'll add a resume function in the next update.
