### ISSUE TITLE
Why not using SAN module during finetuning on RTE (or other pair tasks) 

### ISSUE THREAD

**Issue by ngoyal2707** [namisan/mt-dnn#54]
As per the current `scripts/run_rte.sh`, you are giving `answer_opt=0` for `rte`. I am curious what was the reason of throwing away the `SAN` module for finetuning of the pair tasks and going back to using `pooler`.

1) Is this what you use for glue submission or you use SAN for finetuning for submission?
2) If not, do you know the perf difference?

**Comment by namisan** [comment]
RTE is not stable due to the small training size. For the ensemble model, we use both w/o SAN.

**Comment by ngoyal2707** [comment]
@namisan how about other pairwise tasks like MNLI, QNLI, QQP, MRPC

**Comment by namisan** [comment]
As in our paper, SAN works very well if the training dataset is large, e.g, MNLI/QQP, however, it is not stable on the small task. In our single model setting, we use SAN on most of tasks. For ensemble, we want diverse predictions, thus we use both SAN and linear projection.
