### ISSUE TITLE
What's the difference between mt-dnn and finetune the same BERT in each task one by one?

### ISSUE THREAD

**Issue by HaodaY** [namisan/mt-dnn#55]
If I first finetune BERT in task_1, then finetune the same BERT in task_2, and final get the finetuend BERT in task_1 & task_2. Is it same as mt-dnn in task_1 & task_2?

**Comment by namisan** [comment]
For mt-dnn, it is only a matter of how to schedule a task and how to sample a mini-batch within a task.  Our current training approach is pretty simple. You can make it more fancy.
