### ISSUE TITLE
Why is time prolonged in multi-GPU training?

### ISSUE THREAD

**Issue by 156aasdfg** [namisan/mt-dnn#59]
I wonder why adding the number of gpus will increase the remaining training time under the same batch_size condition.
![image](https://user-images.githubusercontent.com/29187343/60499773-b2a64700-9ceb-11e9-91ce-5c7d6882d0dd.png)
The picture above shows the situation of a single GPU.When I used 4 v100s to train the network, the time increased to two hours.

**Comment by namisan** [comment]
The first estimation may be not accurate. Could you check after a few iterations? Further, make sure you use a proper batch size.
