### ISSUE TITLE
Use task specific layers after training

### ISSUE THREAD

**Issue by v1nc3nt27** [namisan/mt-dnn#60]
Is there any way to load the model after training and classify based on the task-specific dense layers (I assume for each task a specific dense layer is learned for classification) or are these not stored with the model.pt file and lost? E.g. if one wants to predict classes for samples of an unseen dataset on the, let's say, specific MNLI dense layer.

**Comment by v1nc3nt27** [comment]
Nvm, they are stored and can be loaded for predictions.

**Comment by Rajratnpranesh** [comment]
> Is there any way to load the model after training and classify based on the task-specific dense layers (I assume for each task a specific dense layer is learned for classification) or are these not stored with the model.pt file and lost? E.g. if one wants to predict classes for samples of an unseen dataset on the, let's say, specific MNLI dense layer.

**_Did you found the way to run specific task on mt-dnn. For example if I just want to run single sentence classification task on CoLa dataset. Please help.
Thank You_**
