### ISSUE TITLE
What is the range of score in stsb task?

### ISSUE THREAD

**Issue by vikas-baghel** [namisan/mt-dnn#62]
While printing the values of test_predictions in stsb task I was getting 0 for all cases. Then I printed the scores. I thought the scores were from 0 to 5 where 5 representing most similar but when I printed them I found that some of the similarity scores were negative. Can you clarify what is the range of similarity score.
Another problem I am getting is that the test results change if I run the model again( I am not training the model, I am just predicting the test set). I thought it was due to the dropout, so I made the dropout 0 but I am still getting different results every time I ran it.
I even saw that you have used self.network.eval() which makes the network in testing mode thus even if there is any dropout layer then it ignores it.

**Comment by namisan** [comment]
The output is from -infinity to +infinity, which is the raw output of linear projection.
