### ISSUE TITLE
Would you add the gradient accumulcation step?

### ISSUE THREAD

**Issue by qianqianhu577** [namisan/mt-dnn#63]
Hi, 
I'm tring to reproduce the reported result. Since we don't have many large RAM GPUs, adding gradient accumulation steps would be of great help. Should the standard gradient accumulation version be modified to adapt to multi-task setting? 

Thanks.

**Comment by namisan** [comment]
We'll consider it.

**Comment by namisan** [comment]
We have this support now.

**Comment by qianqianhu577** [comment]
Thanks.
