### ISSUE TITLE
A question about 'factor'

### ISSUE THREAD

**Issue by fyubang** [namisan/mt-dnn#66]
Thanks for your great work!
Actually, I am curious about how to define the value of factor for each task, could you share some experience about it ?
Thank you !

**Comment by namisan** [comment]
Which factor?

**Comment by fyubang** [comment]
> Which factor?

![image](https://user-images.githubusercontent.com/25549892/60953938-b7dd4480-a330-11e9-8653-31e4d8d7491d.png)
This one, the weight of task

**Comment by namisan** [comment]
This is a sample weight measuring how important each sample it is.
