### ISSUE TITLE
multi-task text classification

### ISSUE THREAD

**Issue by zhentaoCoding** [namisan/mt-dnn#81]
How can I use this code do multi-task text classification?

**Comment by namisan** [comment]
you may follow cola task: https://github.com/namisan/mt-dnn/blob/master/experiments/glue/glue_task_def.yml#L1

**Comment by Rajratnpranesh** [comment]
> How can I use this code do multi-task text classification?

Did you found the way to run specific task on mt-dnn. For example if I just want to run single sentence classification task on CoLa dataset. Please help. 
Thank You

**Comment by antgr** [comment]
> ay to run specific task on mt-dnn. For example if I just want to run single sentence classification task on CoLa dataset. Please help.

If I understand correctly, you can check 
for example what you want is something like script scripts/run_stsb.sh for stsb:
inside the script you can see:
train_datasets="stsb"
test_datasets="stsb"
Similarly, you can check scripts/run_mt_dnn.sh
where you can see:
train_datasets="mnli,rte,qqp,qnli,mrpc,sst,cola,stsb"
test_datasets="mnli_matched,mnli_mismatched,rte"
Now here you could change the tasks, for example you could keep only cola, or create a similar script like for stsb.
