### ISSUE TITLE
segment default

### ISSUE THREAD

**Issue by moonlight1776** [namisan/mt-dnn#83]
Hi all,
when I run  run_stsb.sh, an error occurred.
Does anybody have the same issue?
![image](https://user-images.githubusercontent.com/23304341/63271848-911a1280-c2cd-11e9-939b-c45f637249ca.png)

**Comment by moonlight1776** [comment]
Incompatibility in apex and GCC.
fixed

**Comment by Newbeeer** [comment]
Hi,

I have exactly the same issue. Could you please give me some hint on how to fix the Incompatibility?

Thanks!
Yilun
