### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by avinashsai** [namisan/mt-dnn#89]
Hi,
Congratulations on your amazing work.

I wanted to fine tune the model on a custom dataset. Can you please provide instructions on how to train the model on custom dataset.

Thank you.

**Comment by antgr** [comment]
Can you provide more info, about your task?

**Comment by namisan** [comment]
Please follow the tutorial.
https://github.com/namisan/mt-dnn/tree/master/tutorials

**Comment by viethoang303** [comment]
I don't see the tutorial now. Can you upload it again? 

Thank you.

> Please follow the tutorial. https://github.com/namisan/mt-dnn/tree/master/tutorials
