### ISSUE TITLE
SAN_META and generate_decoder_opt

### ISSUE THREAD

**Issue by saiabishek1** [namisan/mt-dnn#9]
Can you please tell me the use of the SAN_META dictionary and generate_decoder_opt function in the label_map.py file?

**Comment by namisan** [comment]
SAN_META is to define whether the task can use the SAN net: 0 indicating we cannot use SAN in this task, e.g., regression. There is a small cleaning bug, and we'll fix it soon and add some comments in the code.

**Comment by ZhaofengWu** [comment]
Looks like by default SciTail does not use SAN, because it uses the default value for `--answer_opt`, which is 0. Why is that?
