### ISSUE TITLE
Which piece of code is the Ensemble and Knowledge Distillation?

### ISSUE THREAD

**Issue by dingjianxing** [namisan/mt-dnn#90]
Hello, Thanks for your great work! I have three questions.
       Q1: Which piece of code is the Ensemble?
       Q2: Is this code used for Knowledge Distillation? 
              【batcher.py】
                # soft label generated by ensemble models for knowledge distillation
                if self.soft_label_on and (batch[0].get('softlabel', None) is not None):
                    sortlabels = [sample['softlabel'] for sample in batch]
                    sortlabels = torch.FloatTensor(sortlabels)
                    batch_info['soft_label'] = self.patch(sortlabels.pin_memory()) if self.gpu else sortlabels
        Q3: How is the 'softlabel' added in 'batch[0]'?

Looking forward to your reply. Thanks very much.

**Comment by namisan** [comment]
1. Ensemble should be easy: just use different config, e.g., random seeds or BERT/RoBERTa.
2. softlabel is used for KD.
