### ISSUE TITLE
Could you release MT-DNN no-fine-tune checkpoint with task layers?

### ISSUE THREAD

**Issue by yaolu** [namisan/mt-dnn#93]
Hi,

Is it possible to release MT-DNN no-fine-tune checkpoint?

Currently released mt-dnn-large.pt only contains shared layers, lacks task-specific layers.

Thanks!

**Comment by yaolu** [comment]
@namisan Thanks!

**Comment by namisan** [comment]
I forget from which checkpoint I dumped the shared layers. I have several deadlines and will search them for you later.

**Comment by yaolu** [comment]
Hi,

I tried to fix the released mt-dnn model's parameter, then do multitask finetune on only task-specific layers to reproduce your mt-dnn without task-specific finetune result.

But I cannot reproduce the result claimed in the paper.
e.g. In the paper, cola dev MCC should be around 60, while my result is 48,  drops by 10 points.
stsb dev 90, my result is 75, dropped by 15 points.

Would you mind take a look to see if there's something wrong with my settings?

Thanks!

Here are my settings.



BERT_PATH="mt_dnn_models/mt_dnn_large_uncased.pt"
DATA_DIR="data/mt_dnn_uncased_lower"

answer_opt=0
optim="adamax"
grad_clipping=0
global_grad_clipping=1
lr="2e-5"

model_dir="checkpoints/${prefix}_${optim}_answer_opt${answer_opt}_gc${grad_clipping}_ggc${global_grad_clipping}_${tstr}_fp16"
log_file="${model_dir}/log.log"
python train.py --data_dir ${DATA_DIR} --init_checkpoint ${BERT_PATH} --batch_size ${BATCH_SIZE} --output_dir ${model_dir} --log_file ${log_file} --answer_opt ${answer_opt} --optimizer ${optim} --train_datasets ${train_datasets} --test_datasets ${test_datasets} --grad_clipping ${grad_clipping} --global_grad_clipping ${global_grad_clipping} --learning_rate ${lr} --multi_gpu_on --grad_accumulation_step 1 --fp16 --update_bert_opt 1

**Comment by namisan** [comment]
COLA is pretty unstable. Pls don't use FP16.

**Comment by Rajratnpranesh** [comment]
> Hi,
> 
> Is it possible to release MT-DNN no-fine-tune checkpoint?
> 
> Currently released mt-dnn-large.pt only contains shared layers, lacks task-specific layers.
> 
> Thanks!

Did you found the way to run specific task on mt-dnn. For example if I just want to run single sentence classification task on CoLa dataset. Please help.
Thank You

**Comment by yaolu** [comment]
> COLA is pretty unstable. Pls don't use FP16. Why do you not update bert? It is not finetuning anymore.

I didn't mean to finetune it. I want to get the no-fine-tune checkpoint with task layers.

While the current ckpt provided in this repo is the stripped task layer version. Therefore if I fix the bert part, then I can optimize to get the task layer parameters compatible no-finetune bert.

I failed to get paper reported results on 2 datasets, for the remaining, they can work well.
