### ISSUE TITLE
How to use final pre-trained model to get entailment scores?

### ISSUE THREAD

**Issue by justachetan** [namisan/mt-dnn#94]
Hi @namisan!

I came across your repository from paperswithcode.com, while looking for SOTA NLI models. I am trying to get entailment scores between a given premise and hypothesis using your pre-trained models.

Could you please provide the steps I would need to follow to achieve this? I went through your README but could not figure out how this could be done. The README seems to focus more on training our own model from scratch or on reproducing the results of your paper, but there does not seem to be any API provided for using the pre-trained model to get entailment scores.

If I have missed any part of the source code or README that might be talking about this, could you kindly point me to it? If this has already not been covered in the README or implemented at all, I would be more than happy to implement and document this API if you could just guide me on how to start.

I would be extremely grateful if you could kindly help me out in this. 

Thanks!

Best,
Aditya

**Comment by namisan** [comment]
I am very busy in these days and will release the pretrained NLI models once I have time. 
thanks,
Xiaodong
