### ISSUE TITLE
Could you advise what kind of computation resource is required?  Estimated training time

### ISSUE THREAD

**Issue by studiocardo** [namisan/mt-dnn#95]
Hi Namisan

The code page said that you use 4 V100 to train the a toy example and 8 V100 to fine-tune MT-DNN.  Could you provide the rough estimate for the training time required for both cases?  

Thank you!

SH

**Comment by namisan** [comment]
If jointly training the whole GLUE with 8 V100 using FP32, it takes 2 days. I forgot the time of 4 V100.
