### ISSUE TITLE
How to set the optimizer to sgd

### ISSUE THREAD

**Issue by JingyangXu1991** [namisan/mt-dnn#97]
Hi，
I want to use MTDNN train a single bert model use ‘sgd’ optimizer，but an error occured as follows：
self.optimizer = optim.sgd(optimizer_parameters, opt['learning_rate'],
AttributeError: module 'torch.optim' has no attribute 'sgd
I want to know how to use  optimizer sgd correctly？
best regard！

**Comment by namisan** [comment]
It should be SGD instead of sgd. Solved.
thanks, 
-xiaodong
