### ISSUE TITLE
KeyError in Extracting embeddings with pretrained model

### ISSUE THREAD

**Issue by BowenBao** [namisan/mt-dnn#98]
Thanks for sharing the pretrained model!

I tried the below steps in the README.md

1. Download data and pretrained model. ```> sh download.sh```
2. Run Extract embeddings
```>python extractor.py  --do_lower_case --finput input_examples\single-input.txt --foutput input_examples\single-output.json --bert_model bert-base-uncased --checkpoint mt_dnn_models\mt_dnn_base_uncased.pt``` (had to change to ```mt_dnn_base_uncased.pt``` instead of ```mt_dnn_base.pt``` because only the first one is downloaded.)

And it gives error 

```
Traceback (most recent call last):
  File "extractor.py", line 244, in <module>
    main()
  File "extractor.py", line 214, in main
    num_train_step=num_all_batches)
  File "/home/bowbao/repos/models/mt-dnn/mt_dnn/model.py", line 29, in __init__
    self.network = SANBertNetwork(opt)
  File "/home/bowbao/repos/models/mt-dnn/mt_dnn/matcher.py", line 26, in __init__
    self.encoder_type = opt['encoder_type']
KeyError: 'encoder_type'
```

**Comment by namisan** [comment]
I forget to update this file after adding roberta. I'll update it soon.

**Comment by namisan** [comment]
updated

**Comment by BowenBao** [comment]
Thank you!
